// API route for creating Stripe checkout sessions.
//
// This endpoint accepts POST requests containing details of the
// desired checkout: user plan, team subscription or boost purchase.
// It responds with the session id and URL generated by Stripe.  For
// free plans no session is created; the response includes a
// `free: true` indicator instead.

import { NextResponse } from 'next/server';

const {
  createUserPlanSession,
  createTeamSubscriptionSession,
  createBoostSession,
} = require('../../../../src/server/billing/checkoutService');

export async function POST(req) {
  try {
    const body = await req.json();
    const user = body.user;
    if (!user || !user._id) {
      return NextResponse.json({ error: 'User information is required' }, { status: 400 });
    }
    // User plan checkout
    if (body.plan) {
      const session = await createUserPlanSession(user, body.plan);
      if (!session) {
        return NextResponse.json({ free: true });
      }
      return NextResponse.json({ id: session.id, url: session.url });
    }
    // Team subscription checkout
    if (body.teamId) {
      const activePlayers = Number(body.activePlayers) || 0;
      const socials = body.socials === true || body.socials === 'true' || body.socials === 1 || body.socials === '1';
      const team = { _id: body.teamId };
      const session = await createTeamSubscriptionSession(user, team, activePlayers, socials);
      return NextResponse.json({ id: session.id, url: session.url });
    }
    // Boost checkout
    if (body.duration) {
      const { targetType, targetId, duration } = body;
      const session = await createBoostSession(user, targetType, targetId, duration);
      return NextResponse.json({ id: session.id, url: session.url });
    }
    return NextResponse.json({ error: 'Invalid checkout request' }, { status: 400 });
  } catch (err) {
    return NextResponse.json({ error: err.message }, { status: 400 });
  }
}